drivers/gpio: use gpio-msm-v3, remove versions 1 & 2
The files are pretty much identical anyways, so it should be an easy
drop-in replacement for v2 and it solves an undefined reference to
__msm_gpio_set_subsys_id from coresight.